import numpy as np
from matplotlib.ticker import ScalarFormatter

class Config:
    DATA_DIR = '../01_src/01_data/02_json'
    EVENT_FILES = {
        "tHbq": "Ntuple_tHbq_22M.json",
        "tt": "Ntuple_tt_22M.json",
        "ttbb": "Ntuple_ttbb_65979470.json",
        "ttH": "Ntuple_ttH_22M.json",
        "tZbq": "Ntuple_tZbq_22M.json",
        "ttZ": "Ntuple_ttZ_22M.json",
        "ttW": "Ntuple_ttW_22M.json"
    }

    SIGNAL_CHANNEL_NAME = 'tHbq'
    VARIABLES_DESCRIPTION = {
        'mass_3jet': 'Invariant mass of three jets',
        'n_bjet': 'Number of jets generated by b-quarks',
        'sphericity_all_jets': 'A measure of the uniformity of jet distribution in space',
        'aplanarity_all_jets': '',
        'sphericity_lnu': 'A measure of the uniformity of jet distribution in space',
        'aplanarity_lnu': '',
        'delta_eta_top_higgs': 'Difference between the pseudorapidities of the top quark and the Higgs boson',
        'delta_eta_top_fwd': 'Pseudo-rapidity difference between the t-quark and the front jet',
        'delta_eta_top_tag': '',
        'mass_th': 'Invariant mass of the t-quark and Higgs boson',
        'mass_higgs': 'Recovered mass of the Higgs boson',
        'mass_top': 'Recovered t-quark mass',
        'pt_fwd': 'Transverse momentum of a quark scattered forward',
        'pt_tag': '',
        'eta_fwd': '',
        'eta_tag': '',
        'mass_higgs_fwd': 'Invariant mass of the Higgs boson and the front jet',
        'mass_higgs_tag': '',
        'mass_top_fwd': 'Invariant mass of the front jet and t quark',
        'mass_top_tag': '',
        'q_lead': 'Charge of the leading lepton',
        'n_nonbjet': '',
        'fwjets2': '',
        'fwlnujet1': 'First Fox-Wolfram moment composed of jets only',
        'deltaR_bjetmax_fwd': 'Difference between the pseudo-velocities of the front jet and the b-jet with the highest pt',
        'deltaR_bjetmax_tag': '',
        'deltaR_nearest_bjet_fwd': 'The difference between the pseudo-velocities of the front jet and the b-jet closest to it',
        'deltaR_nearest_bjet_tag': '',
        'max_pt_nonbjet': 'Highest transverse impulse among light jets',
        'mT_all_jets': 'Transverse Mass of all jets',
        'eta_lead': '',
        'sum_pt_jets': 'Algebraic Sum of all transverse momenta',
        'energy_third_bjet': '',
        'delta_phi_higgs_top': '',
        'delta_eta_higgs_fwd': '',
        'delta_eta_higgs_tag': '',
        'pt_higgs': '',
        'max_pt_bjet': '',
        'pt_second_bjet': 'Energy of the b-jet second in transverse momentum',
        'eta_higgs': '',
        'eta_second_bjet': '',
        'm_max_bjet': '',
        'eta_max_bjet': '',
        'mass_higgs_central_jet': 'Invariant mass of the Higgs boson and the central light jet',
        'n_forward_jet': '',
        'n_central_jet': '',
        'n_jet': '',
        'chi2_min': 'Quality of Higgs and Top Mass determinations',
        'flag_correct_bjet_set': '',
        'deltaR_qq_W_max_pt': '',
        'deltaR_qq_W_nearest_mass_W': '',
        'pt_lead': ''
    }
    EXCLUDED_VARIABLES = ['flag_correct_bjet_set', 'n_bjet', 'sphericity_all_jets', 'aplanarity_all_jets',
                          'aplanarity_lnu', 'delta_eta_top_fwd', 'n_nonbjet', 'delta_eta_higgs_fwd', 'pt_higgs',
                          'pt_tag']
    LUMINOSITY = 139.0
    CROSS_SECTIONS = {
        "tHbq": 12.45,
        "tt": 194_600 * 1.886,
        "ttbb": 4_807,
        "ttH": 103.4,
        "tZbq": 31.37,
        "ttZ": 34.1,
        "ttW": 212.2
    }
    GENERATED_EVENTS_NUMBER = {
        "tHbq": 22_000_000,
        "tt": 220_000_000,
        "ttbb": 65_979_470,
        "ttH": 22_000_000,
        "tZbq": 22_000_000,
        "ttZ": 22_000_000,
        "ttW": 22_000_000
    }
    PRESELECTION_EVENTS_NUMBER = {
        "tHbq": 2_567_765,
        "tt": 986_383,
        "ttbb": 1_941_358,
        "ttH": 2_948_179,
        "tZbq": 2_336_142,
        "ttZ": 2_532_704,
        "ttW": 157_993
    }

    # PLOTS #
    FONT_SIZE = 14
    BIN_EDGES = np.linspace(0, 1, 40)
    BINNING_RANGES = {
        'mass_3jet': (150, 0, 2000),
        'n_bjet': (6, 0, 6),
        'sphericity_all_jets': (200, 0, 1),
        'aplanarity_all_jets': (100, 0, 0.25),
        'sphericity_lnu': (200, 0, 1),
        'aplanarity_lnu': (100, 0, 0.25),
        'delta_eta_top_higgs': (200, 0, 10),
        'delta_eta_top_fwd': (200, 0, 10),
        'delta_eta_top_tag': (200, 0, 10),
        'mass_th': (200, 0, 2000),
        'mass_higgs': (200, 0, 1000),
        'mass_top': (200, 0, 1000),
        'pt_fwd': (100, 0, 300),
        'pt_tag': (100, 0, 400),
        'eta_fwd': (100, -6, 6),
        'eta_tag': (100, -6, 6),
        'mass_higgs_fwd': (200, 0, 2000),
        'mass_higgs_tag': (200, 0, 2000),
        'mass_top_fwd': (200, 0, 2000),
        'mass_top_tag': (200, 0, 2000),
        'q_lead': (6, -3, 3),
        'n_nonbjet': (10, 0, 10),
        'fwjets2': (100, 0, 1),
        'fwlnujet1': (100, 0, 1),
        'deltaR_bjetmax_fwd': (100, 0, 8),
        'deltaR_bjetmax_tag': (100, 0, 8),
        'deltaR_nearest_bjet_fwd': (100, 0, 7),
        'deltaR_nearest_bjet_tag': (100, 0, 7),
        'max_pt_nonbjet': (100, 0, 500),
        'mT_all_jets': (400, 0, 4000),
        'eta_lead': (100, -3, 3),
        'sum_pt_jets': (200, 0, 1500),
        'energy_third_bjet': (100, 0, 400),
        'delta_phi_higgs_top': (100, 0, 5.0),
        'delta_eta_higgs_fwd': (200, 0, 10),
        'delta_eta_higgs_tag': (200, 0, 10),
        'pt_higgs': (100, 0, 500),
        'max_pt_bjet': (100, 0, 500),
        'pt_second_bjet': (100, 0, 500),
        'eta_higgs': (100, -6, 6),
        'eta_second_bjet': (100, -6, 6),
        'm_max_bjet': (100, 0, 100),
        'eta_max_bjet': (100, -6, 6),
        'mass_higgs_central_jet': (200, 0, 1000),
        'n_forward_jet': (10, 0, 10),
        'n_central_jet': (10, 0, 10),
        'n_jet': (15, 0, 15),
        'chi2_min': (100, 0, 50),
        'flag_correct_bjet_set': None,
        'deltaR_qq_W_max_pt': (100, 0, 10),
        'deltaR_qq_W_nearest_mass_W': (100, 0, 10),
        'pt_lead': (100, 0, 300)
    }
    PLOT_SIZE = (6, 5)
    POWER_LIMITS = (-2, 2)

    MY_FORMATTER = ScalarFormatter(useMathText=True)
    MY_FORMATTER.set_scientific(True)
    MY_FORMATTER.set_powerlimits(POWER_LIMITS)

    # NEURAL NETWORK #
    WEIGHTS_SEED_NUMBER = 35
    PERMUTATION_REPEATS = 10
