class Config:
    ROOT_PATH = 'data/root/'
    JSON_PATH = 'data/json/'
    FOLDER_PATH = 'histograms/'
    NECESSARY_BRANCHES = ['lead_lep_charge', 'N_b', 'HT_alljets', 'delta_eta_tH', 'sphresity_alljets',
                          'sphresity_lnu4maxje', 'sphresity_allobjects', 'higgs_m', 'mass_tH', 'delta_eta_FWD_t',
                          'min_chi', 'mass_H_CenJet', 'mass_H_FWD', 'FWD_pt', 'fwm1', 'top_m', 'DeltaR_qqW',
                          'RapGap_maxptb', 'RapGap_closest', 'Central_non_b_maxpt_pt', 'FWD_m', 'jet_b2_e', 'W_T_m',
                          'InvMass_3Jets']

    VARIABLES_DESCRIPTION = {
        'lead_lep_charge': 'Charge of the leading lepton',
        'N_b': 'Number of jets generated by b-quarks',
        'HT_alljets': 'Algebraic Sum of all transverse momenta',
        'delta_eta_tH': 'Difference between the pseudorapidities of the top quark and the Higgs boson',
        'sphresity_alljets': 'A measure of the uniformity of jet distribution in space',
        'sphresity_lnu4maxje': 'A measure of the uniformity of jet distribution in space',
        'sphresity_allobjects': 'A measure of the uniformity of jet distribution in space',
        'higgs_m': 'Recovered mass of the Higgs boson',
        'mass_tH': 'Invariant mass of the t-quark and Higgs boson',
        'delta_eta_FWD_t': 'Pseudo-rapidity difference between the t-quark and the front jet',
        'min_chi': 'Quality of Higgs and Top Mass determinations',
        'mass_H_CenJet': 'Invariant mass of the Higgs boson and the central light jet',
        'mass_H_FWD': 'Invariant mass of the Higgs boson and the front jet'
    }
